server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.43.142:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: d^uK^AH&?kWc2G-h
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true