-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 11:25:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Major` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  CONSTRAINT `Major`
    FOREIGN KEY (`Major`)
    REFERENCES `mydb`.`Major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idAdmin_UNIQUE` ON `mydb`.`Admin` (`idAdmin` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Major_idx` ON `mydb`.`Admin` (`Major` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `content` VARCHAR(45) NOT NULL,
  `identity` TINYINT(2) NOT NULL,
  `questionId` INT NOT NULL,
  `stuId` INT NOT NULL,
  `adminId` INT NOT NULL,
  PRIMARY KEY (`content`, `identity`, `questionId`, `stuId`, `adminId`),
  CONSTRAINT `answer`
    FOREIGN KEY (`questionId`)
    REFERENCES `mydb`.`Question` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stuId`
    FOREIGN KEY (`stuId`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adminId`
    FOREIGN KEY (`adminId`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `answer_idx` ON `mydb`.`Answer` (`questionId` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `stuId_idx` ON `mydb`.`Answer` (`stuId` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `adminId_idx` ON `mydb`.`Answer` (`adminId` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Classification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Classification` (
  `idCourse` INT NOT NULL,
  `Courschema` INT NOT NULL,
  `Compulsory` TINYINT NULL,
  `RuXi` TINYINT NULL,
  PRIMARY KEY (`idCourse`),
  CONSTRAINT `idCourse`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Courschema`
    FOREIGN KEY (`Courschema`)
    REFERENCES `mydb`.`Courschema` (`Courschema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idClassification_UNIQUE` ON `mydb`.`Classification` (`idCourse` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`College` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`College` (
  `idCollege` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCollege`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCollege_UNIQUE` ON `mydb`.`College` (`idCollege` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Courschema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courschema` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Courschema` (
  `Courschema` INT NOT NULL,
  `Year` INT NOT NULL,
  `Major` INT NOT NULL,
  `Deparment` INT NOT NULL,
  `Foreign` TINYINT NULL,
  `1+3` TINYINT NULL,
  `major_elec` INT NOT NULL,
  `HU_elec` INT NOT NULL,
  `SS_elec` INT NOT NULL,
  `AR_elec` INT NOT NULL,
  `political` INT NOT NULL,
  PRIMARY KEY (`Courschema`),
  CONSTRAINT `Year`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`Year` (`idYear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Major2`
    FOREIGN KEY (`Major`)
    REFERENCES `mydb`.`Major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Department2`
    FOREIGN KEY (`Deparment`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Courschema_UNIQUE` ON `mydb`.`Courschema` (`Courschema` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Year_idx` ON `mydb`.`Courschema` (`Year` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Major_idx` ON `mydb`.`Courschema` (`Major` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Department_idx` ON `mydb`.`Courschema` (`Deparment` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` INT NOT NULL,
  `Code` VARCHAR(10) NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  `Department` INT NOT NULL,
  `Intro` VARCHAR(45) NOT NULL,
  `Credit` DECIMAL(2) NOT NULL,
  `Spring` TINYINT NULL,
  `Autumn` TINYINT NULL,
  `Summer` TINYINT NULL,
  PRIMARY KEY (`idCourse`),
  CONSTRAINT `Department`
    FOREIGN KEY (`Department`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCourse_UNIQUE` ON `mydb`.`Course` (`idCourse` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Department_idx` ON `mydb`.`Course` (`Department` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Course_Eva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_Eva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Eva` (
  `Course` INT NOT NULL,
  `Evaluation` INT NOT NULL,
  PRIMARY KEY (`Course`, `Evaluation`),
  CONSTRAINT `Course`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Eva`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Evaluation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Course_UNIQUE` ON `mydb`.`Course_Eva` (`Course` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Evaluation_UNIQUE` ON `mydb`.`Course_Eva` (`Evaluation` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Course_Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_Semester` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Semester` (
  `Course` INT NOT NULL,
  `Sem` INT NOT NULL,
  PRIMARY KEY (`Course`, `Sem`),
  CONSTRAINT `Course`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sem`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Semster` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Course_UNIQUE` ON `mydb`.`Course_Semester` (`Course` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Sem_UNIQUE` ON `mydb`.`Course_Semester` (`Sem` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Course_Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_Teacher` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Teacher` (
  `Course` INT NOT NULL,
  `Teacher` INT NOT NULL,
  PRIMARY KEY (`Course`, `Teacher`),
  CONSTRAINT `Course`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Teacher`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Teacher` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Course_UNIQUE` ON `mydb`.`Course_Teacher` (`Course` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Teacher_UNIQUE` ON `mydb`.`Course_Teacher` (`Teacher` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `idDepartment` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDepartment_UNIQUE` ON `mydb`.`Department` (`idDepartment` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evaluation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation` (
  `idEvaluation` INT NOT NULL,
  `Content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvaluation`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idEvaluation_UNIQUE` ON `mydb`.`Evaluation` (`idEvaluation` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Major` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Major` (
  `idMajor` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Department` INT NOT NULL,
  PRIMARY KEY (`idMajor`),
  CONSTRAINT `Dpartment`
    FOREIGN KEY (`Department`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idMajor_UNIQUE` ON `mydb`.`Major` (`idMajor` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Dpartment_idx` ON `mydb`.`Major` (`Department` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Prerequisite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prerequisite` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Prerequisite` (
  `Course` INT NOT NULL,
  `idPreCourse` INT NOT NULL,
  PRIMARY KEY (`Course`, `idPreCourse`),
  CONSTRAINT `CourseN`
    FOREIGN KEY (`Course`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PreCourse`
    FOREIGN KEY (`idPreCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PreCourse_UNIQUE` ON `mydb`.`Prerequisite` (`idPreCourse` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CourseN_UNIQUE` ON `mydb`.`Prerequisite` (`Course` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `question` VARCHAR(45) NOT NULL,
  `createrId` INT NOT NULL,
  `questionId` INT NOT NULL,
  PRIMARY KEY (`questionId`),
  CONSTRAINT `stuId`
    FOREIGN KEY (`createrId`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `stuId_idx` ON `mydb`.`Question` (`createrId` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Replacable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Replacable` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Replacable` (
  `idPreCourse` INT NOT NULL,
  `alternative` INT NOT NULL,
  PRIMARY KEY (`idPreCourse`, `alternative`),
  CONSTRAINT `idPreCourse`
    FOREIGN KEY (`idPreCourse`)
    REFERENCES `mydb`.`Prerequisite` (`idPreCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alternative`
    FOREIGN KEY (`alternative`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `alternative_UNIQUE` ON `mydb`.`Replacable` (`alternative` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPreCourse_UNIQUE` ON `mydb`.`Replacable` (`idPreCourse` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Schema_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schema_Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Schema_Course` (
  `Course` INT NOT NULL,
  `Schema` INT NOT NULL,
  PRIMARY KEY (`Course`, `Schema`),
  CONSTRAINT `Course`
    FOREIGN KEY (`Course`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Schema`
    FOREIGN KEY (`Schema`)
    REFERENCES `mydb`.`Courschema` (`Courschema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Schema_idx` ON `mydb`.`Schema_Course` (`Schema` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Semster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Semster` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Semster` (
  `idSemster` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idSemster`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idSemster_UNIQUE` ON `mydb`.`Semster` (`idSemster` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Department` INT NULL,
  `Major` INT NULL,
  `BeginYear` INT NOT NULL,
  `English` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  CONSTRAINT `Department1`
    FOREIGN KEY (`Department`)
    REFERENCES `mydb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Major1`
    FOREIGN KEY (`Major`)
    REFERENCES `mydb`.`Major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BeginYear`
    FOREIGN KEY (`BeginYear`)
    REFERENCES `mydb`.`Year` (`idYear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idStudent_UNIQUE` ON `mydb`.`Student` (`idStudent` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Department_idx` ON `mydb`.`Student` (`Department` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Major_idx` ON `mydb`.`Student` (`Major` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `BeginYear_idx` ON `mydb`.`Student` (`BeginYear` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Student_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Student_course` (
  `idStudent` INT NOT NULL,
  `idCourse` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `idCourse`),
  CONSTRAINT `student1`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `course1_idx` ON `mydb`.`Student_course` (`idCourse` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `idTeacher` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeacher`),
  CONSTRAINT `Department`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Department` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idTeacher_UNIQUE` ON `mydb`.`Teacher` (`idTeacher` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Year` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Year` (
  `idYear` INT NOT NULL,
  PRIMARY KEY (`idYear`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
